"""Add user_journey_state table

Revision ID: 0b2f3c956bcb
Revises: 692adff7c23a
Create Date: 2025-08-05 12:21:38.867517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b2f3c956bcb"
down_revision: Union[str, Sequence[str], None] = "692adff7c23a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_journey_state",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("current_flow_id", sa.String(), nullable=False),
        sa.Column("current_step_identifier", sa.String(), nullable=False),
        sa.Column("last_question_sent", sa.String(), nullable=False),
        sa.Column("user_context", sa.JSON(), nullable=True),
        sa.Column("reminder_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_journey_state_user_id"),
        "user_journey_state",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_journey_state_user_id"), table_name="user_journey_state"
    )
    op.drop_table("user_journey_state")
    # ### end Alembic commands ###
