"""Add reminder_type to user_journey_state

Revision ID: 33064c088dc0
Revises: 921bb3d1813e
Create Date: 2025-08-18 12:19:39.816256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33064c088dc0"
down_revision: Union[str, Sequence[str], None] = "921bb3d1813e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_journey_state", sa.Column("reminder_type", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_journey_state", "reminder_type")
    # ### end Alembic commands ###
