"""pre Initial migration

Revision ID: 593243b75aa3
Revises:
Create Date: 2025-07-10 14:31:27.367496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "593243b75aa3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_end_messaging_history",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("message_number", sa.Integer(), nullable=False),
        sa.Column("user_response", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "assessment_id", "message_number"),
    )
    op.create_index(
        op.f("ix_assessment_end_messaging_history_assessment_id"),
        "assessment_end_messaging_history",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_end_messaging_history_message_number"),
        "assessment_end_messaging_history",
        ["message_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_end_messaging_history_user_id"),
        "assessment_end_messaging_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "assessment_history",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("user_response", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "assessment_id", "question_number"),
    )
    op.create_index(
        op.f("ix_assessment_history_assessment_id"),
        "assessment_history",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_history_question_number"),
        "assessment_history",
        ["question_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_history_user_id"),
        "assessment_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "assessment_result_history",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("crossed_skip_threshold", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "assessment_id"),
    )
    op.create_index(
        op.f("ix_assessment_result_history_assessment_id"),
        "assessment_result_history",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_result_history_user_id"),
        "assessment_result_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chat_history",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("onboarding_history", sa.JSON(), nullable=False),
        sa.Column("anc_survey_history", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_chat_history_user_id"), "chat_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_history_user_id"), table_name="chat_history")
    op.drop_table("chat_history")
    op.drop_index(
        op.f("ix_assessment_result_history_user_id"),
        table_name="assessment_result_history",
    )
    op.drop_index(
        op.f("ix_assessment_result_history_assessment_id"),
        table_name="assessment_result_history",
    )
    op.drop_table("assessment_result_history")
    op.drop_index(
        op.f("ix_assessment_history_user_id"), table_name="assessment_history"
    )
    op.drop_index(
        op.f("ix_assessment_history_question_number"), table_name="assessment_history"
    )
    op.drop_index(
        op.f("ix_assessment_history_assessment_id"), table_name="assessment_history"
    )
    op.drop_table("assessment_history")
    op.drop_index(
        op.f("ix_assessment_end_messaging_history_user_id"),
        table_name="assessment_end_messaging_history",
    )
    op.drop_index(
        op.f("ix_assessment_end_messaging_history_message_number"),
        table_name="assessment_end_messaging_history",
    )
    op.drop_index(
        op.f("ix_assessment_end_messaging_history_assessment_id"),
        table_name="assessment_end_messaging_history",
    )
    op.drop_table("assessment_end_messaging_history")
    # ### end Alembic commands ###
