"""Initial migration

Revision ID: 692adff7c23a
Revises:
Create Date: 2025-07-10 08:17:40.936334

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "692adff7c23a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
