"""Add missing columns to user_journey_state

Revision ID: 921bb3d1813e
Revises: 0b2f3c956bcb
Create Date: 2025-08-14 13:36:15.161329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "921bb3d1813e"
down_revision: Union[str, Sequence[str], None] = "0b2f3c956bcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_journey_state", sa.Column("expected_step_id", sa.String(), nullable=True)
    )
    op.add_column(
        "user_journey_state",
        sa.Column("repair_strikes", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.add_column(
        "user_journey_state",
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_journey_state", "version")
    op.drop_column("user_journey_state", "repair_strikes")
    op.drop_column("user_journey_state", "expected_step_id")
    # ### end Alembic commands ###
