"""Initial migration

Revision ID: b24fda6d4be4
Revises:
Create Date: 2025-07-09 16:43:48.111886

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b24fda6d4be4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessment_history", "score2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessment_history",
        sa.Column("score2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
