"""Add next_question_number to user journey state

Revision ID: e9ef87f0216c
Revises: 33064c088dc0
Create Date: 2025-08-18 15:10:16.285256

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9ef87f0216c"
down_revision: Union[str, Sequence[str], None] = "33064c088dc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_journey_state",
        sa.Column("next_question_number", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_journey_state", "next_question_number")
    # ### end Alembic commands ###
