name: Lint and test
on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          enable-cache: "true"
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependancies
        run: uv sync
      - name: Linter
        run: uv run ruff check
      - name: Formatter
        run: uv run ruff format --check
      - name: Type checker
        run: uv run mypy .
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ai4gd_haystack
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/ai4gd_haystack
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          enable-cache: "true"
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependancies
        run: uv sync
      - name: Test
        run: uv run pytest
      - name: Run migrations
        run: |
          uv run alembic upgrade head
      - name: Check migrations
        run: |
          uv run alembic check | grep 'No new upgrade operations detected.' || (echo 'There are changes which require migrations.' && exit 1)
